# -*- coding: utf-8 -*-
"""
Created on Tue Jul 14 14:09:40 2020

@author: j.khorami
"""

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
from time import sleep 
def fibin(n):
    from time import sleep
    a = 0 
    b = 1
    while a < n:
        #print(a, end=' ')
        # if i haven't add the b i could have lost some values try it yourself.!.
        
        if a % 2 == 0 or b % 2 == 0:
            sleep(0.1)
            print(a)
            print('=====')
            lis=  []
            lis.append(a)
   
        
        ''' 
        this was the mistake i made at the first
        because i didn't notice that i 'm assigning the new value and then add them.
        
        a = b
        b = a + b 
        '''
            
        a ,b = b, a+b 
        
    # this beauty else is loop else not an if else!!!.
    else:
             
        print('the sum is on the top!')
    
       
        
    #print()
    
fibin(400000)